// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD31QG0R1pSPqhp2qTVyaMx1oR8TDfjcss',
    appId: '1:309598755648:web:88015384527111420ef8a5',
    messagingSenderId: '309598755648',
    projectId: 'th5-mobile',
    authDomain: 'th5-mobile.firebaseapp.com',
    storageBucket: 'th5-mobile.firebasestorage.app',
    measurementId: 'G-L97PH4GD4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3mGcpGa9qBM2bBlaVRSezjRXX_dqqtY4',
    appId: '1:309598755648:android:cbda076ae93356490ef8a5',
    messagingSenderId: '309598755648',
    projectId: 'th5-mobile',
    storageBucket: 'th5-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjgwxfaDRffh03uM8fCc1HOOqvHc4j9Q',
    appId: '1:309598755648:ios:142c12fd67acc6070ef8a5',
    messagingSenderId: '309598755648',
    projectId: 'th5-mobile',
    storageBucket: 'th5-mobile.firebasestorage.app',
    iosBundleId: 'com.example.th5Nhom5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjgwxfaDRffh03uM8fCc1HOOqvHc4j9Q',
    appId: '1:309598755648:ios:142c12fd67acc6070ef8a5',
    messagingSenderId: '309598755648',
    projectId: 'th5-mobile',
    storageBucket: 'th5-mobile.firebasestorage.app',
    iosBundleId: 'com.example.th5Nhom5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD31QG0R1pSPqhp2qTVyaMx1oR8TDfjcss',
    appId: '1:309598755648:web:7243a9448c961a710ef8a5',
    messagingSenderId: '309598755648',
    projectId: 'th5-mobile',
    authDomain: 'th5-mobile.firebaseapp.com',
    storageBucket: 'th5-mobile.firebasestorage.app',
    measurementId: 'G-12NEN9RQJG',
  );

}